### ISSUE TITLE
Upgrade from 0.3.1 to 0.5.0 failed.

### ISSUE THREAD

**Issue by spielkind** [eumel8/otc-rds-operator#9] opened 2022-06-24 11:36 UTC
after updating from 0.3.1 to 0.5.0 the pods of the deployment are in a CrashLoopBackoff:

```
{"level":"info","msg":"Sending events to apis","node":"rdsoperator-otc-rds-operator-d6447964f-skzdr","service":"otc-rds-operator","time":"2022-06-24T11:31:29Z"}
{"level":"info","msg":"starting HA controller","node":"rdsoperator-otc-rds-operator-d6447964f-skzdr","service":"otc-rds-operator","time":"2022-06-24T11:31:29Z","type":"runner"}
{"level":"info","msg":"metrics server listening in /metrics:2112","node":"rdsoperator-otc-rds-operator-d6447964f-skzdr","service":"otc-rds-operator","time":"2022-06-24T11:31:29Z","type":"metrics"}
I0624 11:31:29.150164       1 leaderelection.go:248] attempting to acquire leader lease rdsoperator/rdsoperator-otc-rds-operator...
{"level":"info","msg":"leader elected: 'rdsoperator-otc-rds-operator-d6447964f-v2htt'","node":"rdsoperator-otc-rds-operator-d6447964f-skzdr","service":"otc-rds-operator","time":"2022-06-24T11:31:29Z","type":"runner"}
I0624 11:31:46.580398       1 leaderelection.go:258] successfully acquired lease rdsoperator/rdsoperator-otc-rds-operator
{"level":"info","msg":"obtained leadership","node":"rdsoperator-otc-rds-operator-d6447964f-skzdr","service":"otc-rds-operator","time":"2022-06-24T11:31:46Z","type":"runner"}
{"level":"info","msg":"start leading","node":"rdsoperator-otc-rds-operator-d6447964f-skzdr","service":"otc-rds-operator","time":"2022-06-24T11:31:46Z","type":"runner"}
{"level":"info","msg":"starting controller","node":"rdsoperator-otc-rds-operator-d6447964f-skzdr","service":"otc-rds-operator","time":"2022-06-24T11:31:46Z","type":"controller"}
{"level":"info","msg":"starting informers","node":"rdsoperator-otc-rds-operator-d6447964f-skzdr","service":"otc-rds-operator","time":"2022-06-24T11:31:46Z","type":"controller"}
{"level":"info","msg":"waiting for informer caches to sync","node":"rdsoperator-otc-rds-operator-d6447964f-skzdr","service":"otc-rds-operator","time":"2022-06-24T11:31:46Z","type":"controller"}
{"level":"info","msg":"starting 4 workers","node":"rdsoperator-otc-rds-operator-d6447964f-skzdr","service":"otc-rds-operator","time":"2022-06-24T11:31:46Z","type":"controller"}
{"level":"info","msg":"controller ready","node":"rdsoperator-otc-rds-operator-d6447964f-skzdr","service":"otc-rds-operator","time":"2022-06-24T11:31:46Z","type":"controller"}
{"level":"info","msg":"starting smn listener","node":"rdsoperator-otc-rds-operator-d6447964f-skzdr","service":"otc-rds-operator","time":"2022-06-24T11:31:46Z","type":"controller"}
I0624 11:31:47.907513       1 event.go:294] "Event occurred" object="rdsoperator/my-rds" kind="Rds" apiVersion="otc.mcsps.de/v1alpha1" type="Normal" reason="Create" message="This instance is creating."
E0624 11:31:56.944103       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 75 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1500960?, 0x238c830})
	/go/src/otc-rds-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x86
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0005130b0?})
	/go/src/otc-rds-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x75
panic({0x1500960, 0x238c830})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/eumel8/otc-rds-operator/pkg/controller.(*Controller).rdsUpdateStatus(0x16e2f2b?, {0x18f8280, 0xc0000b6b00}, 0x16e2f2b?, 0xc0002d42c0)
	/go/src/otc-rds-operator/pkg/controller/resource.go:670 +0x1ba
github.com/eumel8/otc-rds-operator/pkg/controller.(*Controller).UpdateStatus(0xc0004b0300, {0x18f8280, 0xc0000b6b00}, 0xc0002d42c0)
	/go/src/otc-rds-operator/pkg/controller/resource.go:994 +0x1f6
github.com/eumel8/otc-rds-operator/pkg/controller.(*Controller).processUpdateRds(0xc0004b0300, {0x18f8280, 0xc0000b6b00}, 0xc0002d4000, 0xc0002d42c0)
	/go/src/otc-rds-operator/pkg/controller/worker.go:78 +0x59
github.com/eumel8/otc-rds-operator/pkg/controller.(*Controller).processEvent(0x0?, {0x18f8280?, 0xc0000b6b00?}, {0x1598480?, 0xc0005130b0?})
	/go/src/otc-rds-operator/pkg/controller/worker.go:55 +0x1ae
github.com/eumel8/otc-rds-operator/pkg/controller.(*Controller).processNextItem(0xc0004b0300, {0x18f8280, 0xc0000b6b00})
	/go/src/otc-rds-operator/pkg/controller/worker.go:27 +0xfb
github.com/eumel8/otc-rds-operator/pkg/controller.(*Controller).runWorker(...)
	/go/src/otc-rds-operator/pkg/controller/worker.go:16
github.com/eumel8/otc-rds-operator/pkg/controller.(*Controller).Run.func1()
	/go/src/otc-rds-operator/pkg/controller/controller.go:56 +0x46
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x0?)
	/go/src/otc-rds-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0?, {0x18e5060, 0xc00040fbc0}, 0x1, 0xc000115620)
	/go/src/otc-rds-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x0?, 0x0?)
	/go/src/otc-rds-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x0?, 0x0?, 0x0?)
	/go/src/otc-rds-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x25
created by github.com/eumel8/otc-rds-operator/pkg/controller.(*Controller).Run
	/go/src/otc-rds-operator/pkg/controller/controller.go:55 +0x4d2
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x135e89a]

goroutine 75 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc0005130b0?})
	/go/src/otc-rds-operator/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0xd8
panic({0x1500960, 0x238c830})
	/usr/local/go/src/runtime/panic.go:838 +0x207
github.com/eumel8/otc-rds-operator/pkg/controller.(*Controller).rdsUpdateStatus(0x16e2f2b?, {0x18f8280, 0xc0000b6b00}, 0x16e2f2b?, 0xc0002d42c0)
	/go/src/otc-rds-operator/pkg/controller/resource.go:670 +0x1ba
github.com/eumel8/otc-rds-operator/pkg/controller.(*Controller).UpdateStatus(0xc0004b0300, {0x18f8280, 0xc0000b6b00}, 0xc0002d42c0)
	/go/src/otc-rds-operator/pkg/controller/resource.go:994 +0x1f6
github.com/eumel8/otc-rds-operator/pkg/controller.(*Controller).processUpdateRds(0xc0004b0300, {0x18f8280, 0xc0000b6b00}, 0xc0002d4000, 0xc0002d42c0)
	/go/src/otc-rds-operator/pkg/controller/worker.go:78 +0x59
github.com/eumel8/otc-rds-operator/pkg/controller.(*Controller).processEvent(0x0?, {0x18f8280?, 0xc0000b6b00?}, {0x1598480?, 0xc0005130b0?})
	/go/src/otc-rds-operator/pkg/controller/worker.go:55 +0x1ae
github.com/eumel8/otc-rds-operator/pkg/controller.(*Controller).processNextItem(0xc0004b0300, {0x18f8280, 0xc0000b6b00})
	/go/src/otc-rds-operator/pkg/controller/worker.go:27 +0xfb
github.com/eumel8/otc-rds-operator/pkg/controller.(*Controller).runWorker(...)
	/go/src/otc-rds-operator/pkg/controller/worker.go:16
github.com/eumel8/otc-rds-operator/pkg/controller.(*Controller).Run.func1()
	/go/src/otc-rds-operator/pkg/controller/controller.go:56 +0x46
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x0?)
	/go/src/otc-rds-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x3e
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0x0?, {0x18e5060, 0xc00040fbc0}, 0x1, 0xc000115620)
	/go/src/otc-rds-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xb6
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0x0?, 0x3b9aca00, 0x0, 0x0?, 0x0?)
	/go/src/otc-rds-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x89
k8s.io/apimachinery/pkg/util/wait.Until(0x0?, 0x0?, 0x0?)
	/go/src/otc-rds-operator/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x25
created by github.com/eumel8/otc-rds-operator/pkg/controller.(*Controller).Run
	/go/src/otc-rds-operator/pkg/controller/controller.go:55 +0x4d2
```

**Comment by eumel8** [comment] 2022-06-26 17:16
Yes, there are breaking changes in this very early versions, which caused by non-existing specs and the heavly changes on respurce names.  This could be fixed by upgrade [CRD](https://raw.githubusercontent.com/eumel8/otc-rds-operator/master/manifests/crds/rds.yml) before upgrade Operator, 
but won't work out from this version because the resource name is also changed from `<rds_name>` to `<namespace>_<rds_name>.` 
To save your existing RDS instances, you could 
* [Export/Import](https://github.com/eumel8/otc-rds-operator#importexport) them,
* Rename RDS in OTC
* Apply newer CRD as mentioned
* Wait while all RDS instances update spec/status
* Upgrade Operator

**Closed as completed** 2022-08-04 20:32 UTC
